apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  labels:
    opsrc-datastore: 'true'
    opsrc-provider: redhat
  name: ${REPO_NAME}-registry
  namespace: openshift-${REPO_NAME}
spec:
  image: ${REGISTRY_IMG}:${CHANNEL}-${IMAGE_TAG}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "node-role.kubernetes.io"
            operator: In
            values: 
              - infra
  tolerations:
  - operator: Equal
    key: node-role.kubernetes.io
    value: infra
    effect: PreferNoSchedule
  displayName: ${REPO_NAME}
  icon:
    base64data: ''
    mediatype: ''
  publisher: Red Hat
  sourceType: grpc
