apiVersion: v1
kind: Template
parameters:
- name: REGISTRY_IMG
  required: true
- name: CHANNEL
  required: true
- name: IMAGE_TAG
  required: true
- name: REPO_NAME
  value: REPLACED_BY_SCRIPT
  required: true
- name: ALLOWED_CIDR_BLOCKS_1
  required: true
- name: ALLOWED_CIDR_BLOCKS_2
  required: true
- name: ALLOWED_CIDR_BLOCKS_3
  required: true
- name: ALLOWED_CIDR_BLOCKS_4
  required: true
- name: ALLOWED_CIDR_BLOCKS_5
  required: true
- name: ALLOWED_CIDR_BLOCKS_6
  required: true
- name: ALLOWED_CIDR_BLOCKS_7
  required: true
- name: ALLOWED_CIDR_BLOCKS_8
  required: true
- name: ALLOWED_CIDR_BLOCKS_9
  required: true
metadata:
  name: selectorsyncset-template
objects: []